[package]
name = "pqbench-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Command line frontend for pqbench."

[[bin]]
name = "pqbench"
path = "src/main.rs"

[dependencies]
pqbench = { workspace = true, features = ["iceberg"] }
clap = { version = "4", features = ["derive"] }
glob = "0.3"
tokio = { version = "1", features = ["rt-multi-thread"] }
