[package]
name = "pqbench-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Command line frontend for pqbench."

[features]
default = []
delta = ["pqbench/delta"]
aws = ["pqbench/aws"]
delta-s3 = ["delta", "pqbench/delta-s3", "aws"]

[[bin]]
name = "pqbench"
path = "src/main.rs"

[dependencies]
pqbench = { workspace = true }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }

[dev-dependencies]
tempfile = "3"
